version: '3'

services:
  group-shield-tg-bot:
    image: connectingeverycorner/group-shield-tg-bot:latest
    container_name: group-shield-tg-bot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    environment:
      - BOT_TOKEN=value
      - BOT_USERNAME=value
      - VERIFICATION_EXPIRATION_SECONDS=120
      - RE_JOIN_SECONDS=120
      - LANGUAGE_CODE=en
    volumes:
      - "./config:/app/config"